[versions]
# Required stuff, https://fabricmc.net/develop/
minecraft = "1.21.9"
yarnMappings = "1.21.9+build.1"
fabricLoader = "0.17.3"
fabricApi = "0.134.0+1.21.9"

fabricLanguageKotlin = "1.13.6+kotlin.2.2.20" # https://github.com/FabricMC/fabric-language-kotlin/releases

# Plugins
kotlin = "2.2.20" # Match this to the one above
loom = "1.11-SNAPSHOT" # https://github.com/FabricMC/fabric-loom/releases
modPublish = "1.0.0" # https://github.com/modmuss50/mod-publish-plugin

# Other dependencies
modMenu = "16.0.0-rc.1" # https://github.com/TerraformerscMC/ModMenu/releases
yacl = "3.8.0+1.21.9-fabric" # https://modrinth.com/mod/yacl/versions

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarnMappings" }
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabricLanguageKotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabricLanguageKotlin" }
fabricApi = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
modMenu = { module = "com.terraformersmc:modmenu", version.ref = "modMenu" }
yacl = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl" }

[bundles]


[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
loom = { id = "fabric-loom", version.ref = "loom" }
modPublish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "modPublish"}